-- MySQL Script generated by MySQL Workbench
-- Ne  3. marec 2019, 21:39:14 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema psyche
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema psyche
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psyche` DEFAULT CHARACTER SET utf8 ;
USE `psyche` ;

-- -----------------------------------------------------
-- Table `psyche`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psyche`.`test` (
  `idtest` INT NOT NULL AUTO_INCREMENT,
  `questioncount` INT NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`idtest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psyche`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psyche`.`question` (
  `idquestion` INT NOT NULL AUTO_INCREMENT,
  `testid` INT NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`idquestion`),
  INDEX `fk_question_1_idx` (`testid` ASC),
  CONSTRAINT `fk_question_1`
    FOREIGN KEY (`testid`)
    REFERENCES `psyche`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psyche`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psyche`.`answer` (
  `idanswer` INT NOT NULL AUTO_INCREMENT,
  `questionid` INT NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`idanswer`),
  INDEX `fk_answer_1_idx` (`questionid` ASC),
  CONSTRAINT `fk_answer_1`
    FOREIGN KEY (`questionid`)
    REFERENCES `psyche`.`question` (`idquestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psyche`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psyche`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `age` INT NOT NULL,
  `gender` CHAR NOT NULL,
  `school` VARCHAR(200) NOT NULL,
  `name` VARCHAR(200) NULL,
  `created` DATETIME NULL DEFAULT current_timestamp,
  `testid` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_1_idx` (`testid` ASC),
  CONSTRAINT `fk_user_1`
    FOREIGN KEY (`testid`)
    REFERENCES `psyche`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psyche`.`answered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psyche`.`answered` (
  `idanswered` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `questionid` INT NOT NULL,
  `answerid` INT NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT current_tiemstamp,
  PRIMARY KEY (`idanswered`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
